sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
  - '6'
  - '5'
  - '4'
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
after_script:
  - npm run coveralls
